/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.nbstudio.core.cls;

import javax.swing.AbstractButton;
import javax.swing.ButtonModel;
import javax.swing.JPanel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public final class newfileVisualPanelType extends JPanel {

    private int typeOfClass = -1;
    private final newfileWizardPanelType panel;
    public static final int TYPE_PERSISTENT = 1;
    public static final int TYPE_SERIAL = 2;
    public static final int TYPE_REGISTERED = 3;
    public static final int TYPE_ABSTRACT = 4;
    public static final int TYPE_DATATYPE = 5;
    public static final int TYPE_CSP = 6;
    public static final int TYPE_CUSTOM = 7;

    /**
     * Creates new form newfileVisualPanelType
     */
    public newfileVisualPanelType(final newfileWizardPanelType panel) {
        initComponents();
        this.panel = panel;

        jRadioButton1.addChangeListener(new TypeOfClassListener(TYPE_PERSISTENT));
        jRadioButton2.addChangeListener(new TypeOfClassListener(TYPE_SERIAL));
        jRadioButton3.addChangeListener(new TypeOfClassListener(TYPE_REGISTERED));
        jRadioButton4.addChangeListener(new TypeOfClassListener(TYPE_ABSTRACT));
        jRadioButton5.addChangeListener(new TypeOfClassListener(TYPE_DATATYPE));
        jRadioButton6.addChangeListener(new TypeOfClassListener(TYPE_CSP));
        jRadioButton7.addChangeListener(new TypeOfClassListener(TYPE_CUSTOM));
        
        textSuperClass.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                panel.fireChangeEvent();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                panel.fireChangeEvent();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                panel.fireChangeEvent();
            }
        });
        
        jRadioButton1.doClick();
    }

    @Override
    public String getName() {
        return "Class type";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        textSuperClass = new javax.swing.JTextField();

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton1, org.openide.util.NbBundle.getMessage(newfileVisualPanelType.class, "newfileVisualPanelType.jRadioButton1.text")); // NOI18N

        buttonGroup1.add(jRadioButton2);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton2, org.openide.util.NbBundle.getMessage(newfileVisualPanelType.class, "newfileVisualPanelType.jRadioButton2.text")); // NOI18N

        buttonGroup1.add(jRadioButton3);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton3, org.openide.util.NbBundle.getMessage(newfileVisualPanelType.class, "newfileVisualPanelType.jRadioButton3.text")); // NOI18N

        buttonGroup1.add(jRadioButton4);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton4, org.openide.util.NbBundle.getMessage(newfileVisualPanelType.class, "newfileVisualPanelType.jRadioButton4.text")); // NOI18N

        buttonGroup1.add(jRadioButton5);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton5, org.openide.util.NbBundle.getMessage(newfileVisualPanelType.class, "newfileVisualPanelType.jRadioButton5.text")); // NOI18N

        buttonGroup1.add(jRadioButton6);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton6, org.openide.util.NbBundle.getMessage(newfileVisualPanelType.class, "newfileVisualPanelType.jRadioButton6.text")); // NOI18N

        buttonGroup1.add(jRadioButton7);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton7, org.openide.util.NbBundle.getMessage(newfileVisualPanelType.class, "newfileVisualPanelType.jRadioButton7.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(newfileVisualPanelType.class, "newfileVisualPanelType.jLabel1.text")); // NOI18N

        textSuperClass.setText(org.openide.util.NbBundle.getMessage(newfileVisualPanelType.class, "newfileVisualPanelType.textSuperClass.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textSuperClass, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton7)
                            .addComponent(jLabel1))
                        .addGap(0, 182, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textSuperClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JTextField textSuperClass;
    // End of variables declaration//GEN-END:variables

    public int getTypeOfClass() {
        return typeOfClass;
    }

    public String getSuperClass() {
        return textSuperClass.getText();
    }

    private class TypeOfClassListener implements ChangeListener {

        private final int currentType;

        public TypeOfClassListener(int currentType) {
            this.currentType = currentType;
        }

        @Override
        public void stateChanged(ChangeEvent e) {
            AbstractButton aButton = (AbstractButton) e.getSource();
            ButtonModel aModel = aButton.getModel();
            if (aModel.isSelected()) {
                typeOfClass = currentType;
                panel.fireChangeEvent();
            }
        }
    }
}
