/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.nbstudio.explorer;

import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author daimor
 */
public class EditConnection extends javax.swing.JPanel {

    /**
     * Creates new form EditConnection
     */
    public EditConnection() {
        initComponents();
        setErrorMsg("");
    }

    public void setServerName(String name) {
        this.connName.setText(name);
    }

    public String getServerName() {
        return connName.getText();
    }

    public void setAddr(String addr) {
        this.connAddr.setText(addr);
    }

    public String getAddr() {
        return connAddr.getText();
    }

    public void setSuperPort(int port) {
        superPort.setValue(port);
    }

    public int getSuperPort() {
        return (Integer) superPort.getValue();
    }

    public void setErrorMsg(String msg) {
        errMessage.setText(msg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        connName = new javax.swing.JTextField();
        labelServerName = new javax.swing.JLabel();
        connAddr = new javax.swing.JTextField();
        labelAddress = new javax.swing.JLabel();
        labelSuperPort = new javax.swing.JLabel();
        superPort = new javax.swing.JSpinner();
        labelWebPort = new javax.swing.JLabel();
        webPort = new javax.swing.JSpinner();
        errMessage = new javax.swing.JLabel();
        connNamespace = new javax.swing.JTextField();
        labelNamespace = new javax.swing.JLabel();
        connUser = new javax.swing.JTextField();
        labelUsername = new javax.swing.JLabel();
        connPass = new javax.swing.JPasswordField();
        labelPass = new javax.swing.JLabel();

        connName.setText(org.openide.util.NbBundle.getMessage(EditConnection.class, "EditConnection.connName.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(labelServerName, org.openide.util.NbBundle.getMessage(EditConnection.class, "EditConnection.labelServerName.text")); // NOI18N

        connAddr.setText("localhost");

        org.openide.awt.Mnemonics.setLocalizedText(labelAddress, org.openide.util.NbBundle.getMessage(EditConnection.class, "EditConnection.labelAddress.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(labelSuperPort, org.openide.util.NbBundle.getMessage(EditConnection.class, "EditConnection.labelSuperPort.text")); // NOI18N

        superPort.setModel(new javax.swing.SpinnerNumberModel(1972, 1, 65535, 1));
        superPort.setEditor(new javax.swing.JSpinner.NumberEditor(superPort, ""));
        superPort.setName(""); // NOI18N
        superPort.setOpaque(false);

        org.openide.awt.Mnemonics.setLocalizedText(labelWebPort, org.openide.util.NbBundle.getMessage(EditConnection.class, "EditConnection.labelWebPort.text")); // NOI18N

        webPort.setModel(new javax.swing.SpinnerNumberModel(57772, 1, 65535, 1));
        webPort.setEditor(new javax.swing.JSpinner.NumberEditor(webPort, ""));
        webPort.setName(""); // NOI18N
        webPort.setOpaque(false);

        errMessage.setForeground(new java.awt.Color(253, 43, 43));
        org.openide.awt.Mnemonics.setLocalizedText(errMessage, "errorMesage here");

        connNamespace.setText("USER");

        org.openide.awt.Mnemonics.setLocalizedText(labelNamespace, org.openide.util.NbBundle.getMessage(EditConnection.class, "EditConnection.labelNamespace.text")); // NOI18N

        connUser.setText("_SYSTEM");

        org.openide.awt.Mnemonics.setLocalizedText(labelUsername, org.openide.util.NbBundle.getMessage(EditConnection.class, "EditConnection.labelUsername.text")); // NOI18N

        connPass.setText("SYS");

        org.openide.awt.Mnemonics.setLocalizedText(labelPass, org.openide.util.NbBundle.getMessage(EditConnection.class, "EditConnection.labelPass.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelServerName)
                            .addComponent(labelAddress)
                            .addComponent(labelSuperPort)
                            .addComponent(labelWebPort)
                            .addComponent(labelNamespace)
                            .addComponent(labelUsername)
                            .addComponent(labelPass))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(superPort, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(webPort, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(connName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(connAddr, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(connNamespace, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(connUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(connPass))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelServerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(superPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSuperPort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelWebPort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connNamespace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNamespace))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errMessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField connAddr;
    private javax.swing.JTextField connName;
    private javax.swing.JTextField connNamespace;
    private javax.swing.JPasswordField connPass;
    private javax.swing.JTextField connUser;
    private javax.swing.JLabel errMessage;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelNamespace;
    private javax.swing.JLabel labelPass;
    private javax.swing.JLabel labelServerName;
    private javax.swing.JLabel labelSuperPort;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel labelWebPort;
    private javax.swing.JSpinner superPort;
    private javax.swing.JSpinner webPort;
    // End of variables declaration//GEN-END:variables

    public String getNamespace() {
        return connNamespace.getText();
    }

    public void setNamespace(String namespace) {
        connNamespace.setText(namespace);
    }

    String getUsername() {
        return connUser.getText();
    }

    String getPassword() {
        return new String(connPass.getPassword());
    }
}
